# Loom Workflow Labels
# These labels coordinate the Loom AI agent workflow
# Sync with: ./scripts/install/sync-labels.sh . (from workspace root)
# Or manually: gh label create/edit commands

# Core Workflow States
- name: loom:issue
  description: Approved for work by human (ready for Builder to claim)
  color: "3B82F6"  # blue-500

- name: loom:building
  description: Builder is implementing this issue
  color: "1d76db"  # blue

- name: loom:in-progress
  description: "Issue: Worker implementing | PR: Reviewer reviewing or Worker addressing feedback"
  color: "F59E0B"  # amber-500

# Role-Specific Workflow Labels
- name: loom:building
  description: Builder is implementing this issue
  color: "F59E0B"  # amber-500 - matches other in-progress states

- name: loom:curating
  description: Curator is enhancing this issue
  color: "F59E0B"  # amber-500 - matches other in-progress states

- name: loom:treating
  description: Doctor is fixing this bug or addressing PR feedback
  color: "F59E0B"  # amber-500 - matches other in-progress states

- name: loom:reviewing
  description: Judge is actively reviewing this PR
  color: "F59E0B"  # amber-500 - matches other in-progress states

- name: loom:review-requested
  description: PR ready for Judge to review
  color: "10B981"  # emerald-500

- name: loom:pr
  description: PR approved by Judge, ready for human to merge
  color: "3B82F6"  # blue-500

# Agent Proposal Labels
- name: loom:architect
  description: Architect proposal awaiting user approval
  color: "9333EA"  # purple (violet-600)

- name: loom:hermit
  description: Hermit removal/simplification proposal awaiting user approval
  color: "9333EA"  # purple (violet-600)

- name: loom:curated
  description: Enhanced by Curator, awaiting human approval
  color: "10B981"  # emerald-500

# Status Labels
- name: loom:blocked
  description: Implementation blocked, needs help or clarification
  color: "EF4444"  # red-500

- name: loom:urgent
  description: Critical/blocking issue requiring immediate attention
  color: "DC2626"  # red-600
