blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/rjwalters/loom/discussions
    about: For questions, discussions, and feedback - Issues are for development tasks only
